#include <iostream>
using namespace std;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

// Used second term instead of first term to check for evenness because it had the first occurrence of an even term
// Time Complexity: O(n)? Need to iterate to find terms of Fibonacci sequence

int basic()
{
	int sum = 0;
	int first = 1;
	int second = 2;
	int third = 0;

	while (second <= 4000000)
	{
		third = first + second;
		if (second % 2 == 0)
			sum += second;
		first = second;
		second = third;
	}

	return sum;
}

int main()
{
	cout << "Sum of even terms: " << basic() << endl;
}